{
 "title": "Quarkus",
 "tags": [ "quarkus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(up, job)" },
   {
    "name": "instance",
    "query": "label_values(up{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", instance=\"$instance\"}) by (area)",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{job=\"$job\", instance=\"$instance\"}) by (job, instance)",
     "legendFormat": "live"
    },
    {
     "expr": "sum(jvm_threads_daemon_threads{job=\"$job\", instance=\"$instance\"}) by (job, instance)",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_count{job=\"$job\", instance=\"$instance\"}[1m])) by (job, instance, action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "HTTP Server Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"$job\", instance=\"$instance\"}) by (job, instance, outcome, status, uri)",
     "legendFormat": "{{uri}} {{status}}"
    }
   ]
  }
 ]
}